/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import MainBody from '../components/MainBody'

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {/* body */}
      <MainBody />

      {/* footer */}
      <Footer />
    </div>  
  )
}
